# Python: np.array 的常见操作
1. np.arange(): 生成序列
2. np.linspace(): 生成等差数列
3. np.logspace(): 生成等比数列
4. 生成特殊矩阵
    * no.ones(): 生成都是1的矩阵
    * np.zeros(): 生成都是0的矩阵
    * np.eye()：生成单位矩阵
    * np.diag(): 生成对角矩阵
5. astype():改变数据类型
6. .dtype: 查看数据类型

**1. np.arange(): 生成序列**
一般需要两个参数，分别为起点值和终点值，生成数列不包含终点值。当添加第三个参数时，则是设定每一步的步长，默认为1.

In [1]:
import numpy as np
a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [4]:
b = np.arange(0, 5, 0.5)
b

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

**2. np.linspace():等差数列**
一般有三个参数，包括起点值，终点值和所需数字的个数。生成的数列包括终点值。也可通过设置参数endpoint=False,指定不包括终点值。

c = np.linspace(1, 5, 5)
c

In [6]:
d = np.linspace(1, 5, 5, endpoint = False)
d

array([1. , 1.8, 2.6, 3.4, 4.2])

**3. np.logspace():等比数列**
一般需要三个参数，np.logspace(a, b, c),生成以10^a^为起点，10^b^为终点，生成c个数的等比序列。可通过修改参数base=2修改底数非10的等比数列，默认endpoint=True。

In [8]:
e = np.logspace(0, 3, 4)
e

array([   1.,   10.,  100., 1000.])

In [10]:
f = np.logspace(0, 3, 8, base = 2)
f

array([1.        , 1.34590019, 1.81144733, 2.43802731, 3.28134142,
       4.41635805, 5.94397716, 8.        ])

**4. 生成特殊矩阵**

In [11]:
#生成都是1的矩阵
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [12]:
#生成都是0的矩阵
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [14]:
#生成单位矩阵
np.eye(2, 2)

array([[1., 0.],
       [0., 1.]])

In [15]:
#生成对角矩阵
g = [1, 2, 3]
g1 = np.array([1, 2, 3])
np.diag(g)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
np.diag(g1)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

**5. astype():改变数据类型**
np.array()生成的数组类型都是整数(Int)类型

In [18]:
h = np.array([1, 2, 3, 4], dtype = np.float)
h

C:\Users\yc27965\AppData\Local\Temp\ipykernel_21516\3293962432.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  h = np.array([1, 2, 3, 4], dtype = np.float)


array([1., 2., 3., 4.])

In [19]:
h.astype(int)

array([1, 2, 3, 4])

**6. .dtype:查看数据类型**
type()函数返回的是数组，.dtype函数返回的是数组中内容的数据类型

In [21]:
j = np.array([[1, 2], [3, 4]], dtype = float)

In [22]:
type(j)

numpy.ndarray

In [23]:
j.dtype

dtype('float64')